# Cấu hình docker-compose cho 2 services: wordpress, nginx
# Sử dụng phiên bản mới nhất của nginx từ Docker Hub
# Mount thư mục hiện tại vào các thư mục của container
# Mở cổng 8080 của máy host và map vào cổng 80 của container wordpress
# Mở cổng 80 của máy host và map vào cổng 80 của container nginx

# Sử dụng phiên bản mới nhất của docker-compose
version: '3'

services:

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - wordpress:/var/www/html
    networks:
      - app-network 


  wordpress:
    build:
      context: ./wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    ports:
      - "8080:80"   
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - app-network    

  # db:
  #   image: mysql:latest
  #   restart: always
  #   env_file: .env
  #   environment:
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   ports:
  #     - "9091:3306"  
  #   volumes:
  #     - mysql:/var/lib/mysql

      

volumes:
  mysql:
  wordpress:


networks:
  app-network:
    driver: bridge